{
  "exception": {
    "internal": "Ein Fehler ist aufgetreten! Versuche es spÃ¤ter erneut."
  }
}